version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - my-network
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf  # Make sure the Nginx config is copied if customized

  server:
    build:
      context: ./server
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
