# Generated by Django 5.1.1 on 2024-09-15 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trans_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('trans_tms', models.DateTimeField()),
                ('rc_num', models.CharField(max_length=100)),
                ('client_id', models.CharField(default=uuid.uuid4)),
                ('event_cnt', models.IntegerField()),
                ('location_cd', models.CharField(max_length=100)),
                ('location_id1', models.CharField(blank=True, max_length=50, null=True)),
                ('location_id2', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_nbr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
