# Generated by Django 5.1.1 on 2024-09-15 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='trans_tms',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
