# Generated by Django 5.1.1 on 2024-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_event_location_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='trans_id',
            field=models.UUIDField(editable=False),
        ),
    ]
