# Generated by Django 5.1.1 on 2024-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_event_client_id_alter_event_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trans_id',
            field=models.UUIDField(),
        ),
    ]
