# Generated by Django 5.1.1 on 2024-09-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_event_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_cd',
            field=models.CharField(max_length=100),
        ),
    ]
